default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
exclude: (.terraform.lock.hcl)|(.devcontainer/)|(.cache/)|(artifacts/)
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.3
    hooks:
      - id: go-imports   # replaces go-fmt
        args: [-w]
      - id: go-vet
      - id: go-vet-mod
      - id: go-vet-pkg
      - id: go-vet-repo-mod
      - id: go-vet-repo-pkg
      - id: go-sec-mod
      - id: go-sec-pkg
      - id: go-sec-repo-mod
      - id: go-sec-repo-pkg
      - id: go-critic
      # - id: go-revive
      # - id: go-revive-mod
      # - id: go-revive-repo-mod
