default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
exclude: (.terraform.lock.hcl)|(.devcontainer/)|(.cache/)|(artifacts/)
repos:
  - repo: https://github.com/tchoedak/pre-commit-sql-format
    rev: latest
    hooks:
      - id: format-sql
