---
# Setup: pre-commit install
# Upgrade: pre-commit autoupdate
# Run: pre-commit run --all-files
# https://pre-commit.com/hooks.html
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
exclude: (.terraform.lock.hcl)|(.devcontainer/)|(.cache/)|(artifacts/)
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    # https://github.com/jumanjihouse/pre-commit-hook-yamlfmt#override-defaults
    # https://yaml.readthedocs.io/en/latest/example.html
    rev: 0.1.0     # or specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1     # or higher tag
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict, --config-file, .yamllint.yaml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1     # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-json
        exclude: ^.vscode/
      - id: pretty-format-json
        exclude: ^.vscode/
        args: [--fix]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: forbid-new-submodules
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main]
      - id: requirements-txt-fixer
