default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
exclude: (.terraform.lock.hcl)|(.devcontainer/)|(.cache/)|(artifacts/)
repos:
  - repo: local
    hooks:
      # FIRST TIME SETUP:  GO111MODULE=on go get github.com/zricethezav/gitleaks/v4@latest
      # - id: local-run
      #   name: Scan for secrets
      #   entry: gitleaks --pretty -v
      #   language: system
      - id: gitleaks
        name: gitleaks-scan
        entry: zsh -c docker run -v ${PWD}:/repo zricethezav/gitleaks:latest --path="/repo" --pretty -v
        language: system
        files: ''
      - id: markdownlint
        name: markdownlint-autofix
        entry: zsh -c docker run -i --rm -v ${PWD}:/work tmknom/markdownlint:latest --fix --config ./settings/.markdownlint.yaml # NOTE: Change this to the desired path
        language: system
        files: ''
      - id: shellcheck
        name: shellcheck
        entry: zsh -c docker run --rm -v ${PWD}:/mnt koalaman/shellcheck:stable --format=json
        language: system
        files: ''
      - id: goimports
        name: goimports
        entry: zsh -c docker run --rm -v ${PWD}:/data/ cytopia/goimports:latest -w /data/
        language: system
        files: ''
      - id: revive
        name: revive
        entry: zsh -c $HOME/go/bin/revive -config revive.toml --formatter friendly
        language: system
        files: ''
